name: Deploy Tenant Proxies
on:
  push:
    paths: ['src/apigee/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        tenant: [tenant-a, tenant-b, shared-standard] # Can be dynamic
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/320246485281/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'apigee-sa@apigee-490614.iam.gserviceaccount.com'

      - name: Deploy Proxy to Tenant Env
        run: |
          # Use apigeecli to bundle and deploy
          curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh
          export PATH=$PATH:$HOME/.apigeecli/bin
          
          apigeecli proxies bundle -d ./src/apigee/proxies/my-proxy -n my-proxy
          apigeecli proxies deploy \
            --name my-proxy \
            --env env-${{ matrix.tenant }} \
            --org ${{ vars.APIGEE_ORG }} \
            --token ${{ steps.auth.outputs.access_token }}